// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/admin/admins': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/admins.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/admins.post').default>>>>
    }
    '/api/admin/admins/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/admins/[id].delete').default>>>>
    }
    '/api/admin/flash-sale/config': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/flash-sale/config.post').default>>>>
    }
    '/api/admin/flash-sale/sessions/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/flash-sale/sessions/[id].delete').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/flash-sale/sessions/[id].patch').default>>>>
    }
    '/api/admin/flash-sale/sessions': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/flash-sale/sessions/index.get').default>>>>
    }
    '/api/admin/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/login.post').default>>>>
    }
    '/api/admin/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/logout.post').default>>>>
    }
    '/api/admin/orders/:id/cancel': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/orders/[id]/cancel.patch').default>>>>
    }
    '/api/admin/orders/:id/notify': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/orders/[id]/notify.post').default>>>>
    }
    '/api/admin/orders/:id/upload-proof': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/orders/[id]/upload-proof.post').default>>>>
    }
    '/api/admin/orders/bulk-notify': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/orders/bulk-notify.post').default>>>>
    }
    '/api/admin/orders': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/orders/index.get').default>>>>
    }
    '/api/admin/products/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/products/[id].delete').default>>>>
    }
    '/api/admin/products': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/products/index.post').default>>>>
    }
    '/api/admin/wa-template': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/wa-template.get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/wa-template.put').default>>>>
    }
    '/api/checkout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/checkout.post').default>>>>
    }
    '/api/flash-sale/config': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/flash-sale/config.get').default>>>>
    }
    '/api/products': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/index.get').default>>>>
    }
    '/api/products/status': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/status.get').default>>>>
    }
    '/api/s3-image/**:path': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/s3-image/[...path].get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}